name: chatgpt-telegram-workers
services:
    chatgpt-telegram-workers:
        build: .
        ports:
            - '8787:8787'
        volumes:
            - ./config.json:/app/config.json:ro # change `./config.json` to your local path
            - ./wrangler.jsonc:/app/wrangler.jsonc:ro # change `./wrangler.jsonc` to your local path
        network_mode: 'host' # If you access the proxy port based on the host
