import type { Plugin } from 'vite';

export interface HtmlToStringOptions {
    /** 导出的常量名,默认 PAGE_HTML */
    exportName?: string;
    /** 生成的模块文件名(相对 outDir),默认 index.js */
    fileName?: string;
    /** 是否在 outDir 保留内联后的 HTML(便于本地预览),默认 true */
    keepHtml?: boolean;
}

/**
 * 把 Vite 构建出的单页 HTML 内联成自包含文档,并导出一个 JS 字符串模块。
 *
 * 构建产物中只保留一个 JS chunk 与一个 CSS 文件(见 config 钩子),
 * 它们会被内联进 `index.html`,再从产物里删除;外链 CDN 资源保持原样。
 * 最终 `outDir/<fileName>` 形如:
 *
 *     export const PAGE_HTML = "<!doctype html>...";
 *     export default PAGE_HTML;
 *
 * 这样宿主(core)可以直接把字符串作为页面响应返回,无需任何静态资源路由。
 */
export function htmlToString(options: HtmlToStringOptions = {}): Plugin {
    const exportName = options.exportName ?? 'PAGE_HTML';
    const fileName = options.fileName ?? 'index.js';

    return {
        name: 'ctw:html-to-string',
        apply: 'build',
        // 必须在 Vite 内置 html 插件把资源写入 HTML 之后再处理
        enforce: 'post',

        config() {
            return {
                build: {
                    // 单入口 + 全量内联:产物中不会出现 chunk 或独立资源文件
                    cssCodeSplit: false,
                    modulePreload: false,
                    assetsInlineLimit: Number.MAX_SAFE_INTEGER,
                    rollupOptions: {
                        output: { codeSplitting: false },
                    },
                },
            };
        },

        generateBundle(_outputOptions, bundle) {
            const entry = Object.values(bundle).find(item => item.type === 'asset' && item.fileName.endsWith('.html'));
            if (!entry || entry.type !== 'asset') {
                this.error('[html-to-string] 未找到 HTML 入口产物');
                return;
            }

            let html = String(entry.source);
            const consumed = new Set<string>();
            const scripts = new Map<string, string>();
            const styles = new Map<string, string>();
            for (const item of Object.values(bundle)) {
                if (item.type === 'chunk') {
                    scripts.set(item.fileName, item.code);
                } else if (item.fileName.endsWith('.css')) {
                    styles.set(item.fileName, String(item.source));
                }
            }

            const toFileName = (url: string): string => url.replace(/^\.?\//, '');

            html = html.replace(/<script\b[^>]*\bsrc="([^"]+)"[^>]*><\/script>/g, (tag, src: string) => {
                const code = scripts.get(toFileName(src));
                if (code === undefined) {
                    return tag;
                }
                consumed.add(toFileName(src));
                const attrs = tag.slice('<script'.length, tag.indexOf('>')).replace(/\s*src="[^"]*"/, '');
                return `<script${attrs}>\n${code}\n</script>`;
            });

            html = html.replace(/<link\b[^>]*rel="stylesheet"[^>]*>/g, tag => {
                const href = /href="([^"]+)"/.exec(tag)?.[1];
                const css = href ? styles.get(toFileName(href)) : undefined;
                if (css === undefined) {
                    // 外链 CDN 样式保持原样
                    return tag;
                }
                consumed.add(toFileName(href!));
                return `<style>\n${css}\n</style>`;
            });

            // JS/CSS 已内联,移除对应的预加载提示
            html = html.replace(/<link\b[^>]*rel="modulepreload"[^>]*>/g, '');

            for (const key of consumed) {
                delete bundle[key];
            }
            if (options.keepHtml === false) {
                delete bundle[entry.fileName];
            } else {
                entry.source = html;
            }

            this.emitFile({
                type: 'asset',
                fileName,
                source: `// AUTO-GENERATED by plugin/export-html.ts. Do not edit.\nexport const ${exportName} = ${JSON.stringify(html)};\nexport default ${exportName};\n`,
            });
            this.emitFile({
                type: 'asset',
                fileName: fileName.replace(/\.js$/, '.d.ts'),
                source: `declare const ${exportName}: string;\nexport { ${exportName} };\nexport default ${exportName};\n`,
            });
        },
    };
}
